#BASIC PROBLEMS:

# 1. List all unique cities where customers are located.
SELECT DISTINCT
    customer_city
FROM
    customers;
#------------------------------------------------------------------------------------------------
# 2. Count the number of orders placed in 2017
SELECT 
    COUNT(order_id)
FROM
    orders
WHERE
    YEAR(order_purchase_timestamp) = '2017';

#------------------------------------------------------------------------------------------------    
#3. Find the total sales per category. 
SELECT 
    p.product_category AS Product_Category,
    ROUND(SUM(oi.price), 2) AS Total_Sales,
    COUNT(oi.order_id) AS Total_Orders_Count
FROM 
    order_items oi
LEFT JOIN 
    products p ON oi.product_id = p.product_id
GROUP BY 
    product_category
ORDER BY 
    total_sales DESC;

#------------------------------------------------------------------------------------------------    
#4. Calculate the percentage of orders that were paid in installments. 
SELECT 
    COUNT(DISTINCT CASE WHEN payment_installments > 1 THEN order_id END) AS Installment_Orders,
    COUNT(DISTINCT order_id) AS Total_Orders,
    ROUND(
        100.0 * COUNT(DISTINCT CASE WHEN payment_installments > 1 THEN order_id END) / 
        COUNT(DISTINCT order_id), 2
    ) AS Percentage_Installment_Orders
FROM 
    payments;

#------------------------------------------------------------------------------------------------
#5. Count the number of customers from each state.
SELECT 
    customer_state AS State,
    COUNT(customer_id) AS Number_of_customers
FROM
    customers
GROUP BY customer_state

#------------------------------------------------------------------------------------------------

#INTERMEDIATE PROBLEMS

#1. Calculate the number of orders per month in 2018
SELECT MONTHNAME(order_purchase_timestamp) AS Order_Month,
    COUNT(order_id)
FROM
    orders
where Year(order_purchase_timestamp)='2018'
GROUP BY MONTHNAME(order_purchase_timestamp);

#------------------------------------------------------------------
#2. Find the average number of products per order, grouped by customer city. 
WITH order_item_counts AS (
    SELECT 
        o.order_id,
        o.customer_id,
        COUNT(oi.product_id) AS total_products_in_order
    FROM 
        orders o
    JOIN 
        order_items oi ON o.order_id = oi.order_id
    GROUP BY 
        o.order_id, 
        o.customer_id
)
SELECT 
    c.customer_city,
    ROUND(AVG(oic.total_products_in_order), 2) AS avg_products_per_order,
    COUNT(DISTINCT oic.order_id) AS total_orders_placed
FROM 
    order_item_counts oic
JOIN 
    customers c ON oic.customer_id = c.customer_id
GROUP BY 
    c.customer_city
ORDER BY 
    avg_products_per_order DESC, 
    total_orders_placed DESC;

#--------------------------------------------------------------------------------------------
#3. Calculate the percentage of total revenue contributed by each product category 

Select 
product_category, 
ROUND(SUM(oi.price), 2) AS Category_Revenue,
ROUND(100.0 * sum(oi.price)/sum(sum(oi.price)) over(),2) as Percentage_Contribution
from 
order_items as oi
join 
products as p
on oi.product_id=p.product_id
group by 
product_category
ORDER BY 
    Percentage_Contribution DESC;
 #--------------------------------------------------------------------------------------------
 #4. Identify the correlation between product price and the number of times a product has been purchased.
 #export this below query to power bi and then visualise or use python to find correlation
 SELECT 
    product_id,
    ROUND(AVG(price), 2) AS avg_price,
    COUNT(order_id) AS purchase_count
FROM 
    order_items
GROUP BY 
    product_id
ORDER BY 
    purchase_count DESC;
    
#-----------------------------------------------------------------------------------------------
#5. Calculate the total revenue generated by each seller, and rank them by revenue.
SELECT 
    seller_id,
    ROUND(SUM(price), 2) AS Total_Revenue,
    COUNT(DISTINCT order_id) AS Total_Orders_Fulfilled,
    RANK() OVER (ORDER BY SUM(price) DESC) AS seller_rank
FROM 
    order_items
GROUP BY 
    seller_id
ORDER BY 
    seller_rank ASC;
    
#------------------------------------------------------------------------------------------------------
#ADVANCED PROBLEMS
#1. Calculate the moving average of order values for each customer over their order history. 
WITH order_monetary_values AS (
    SELECT 
        c.customer_unique_id,
        o.order_id,
        o.order_purchase_timestamp,
        SUM(oi.price) AS total_order_value
    FROM 
        orders o
    JOIN 
        order_items oi ON o.order_id = oi.order_id
    JOIN 
        customers c ON o.customer_id = c.customer_id
    GROUP BY 
        c.customer_unique_id, 
        o.order_id, 
        o.order_purchase_timestamp
)
SELECT 
    customer_unique_id,
    order_id,
    order_purchase_timestamp,
    ROUND(total_order_value, 2) AS current_order_value,
    ROUND(
        AVG(total_order_value) OVER (
            PARTITION BY customer_unique_id
            ORDER BY order_purchase_timestamp
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ), 2
    ) AS moving_avg_order_value
FROM 
    order_monetary_values
ORDER BY 
    customer_unique_id, 
    order_purchase_timestamp;
    
#---------------------------------------------------------------
#2. Calculate the cumulative sales per month for each year. 
WITH monthly_sales AS (
    SELECT 
        YEAR(o.order_purchase_timestamp) AS sales_year,
        MONTH(o.order_purchase_timestamp) AS sales_month_num,
        MONTHNAME(o.order_purchase_timestamp) AS sales_month,
        SUM(oi.price) AS monthly_revenue
    FROM 
        orders o
    JOIN 
        order_items oi ON o.order_id = oi.order_id
    WHERE 
        o.order_status NOT IN ('canceled', 'unavailable') -- Excludes unfulfilled orders
    GROUP BY 
        YEAR(o.order_purchase_timestamp),
        MONTH(o.order_purchase_timestamp),
        MONTHNAME(o.order_purchase_timestamp)
)
SELECT 
    sales_year,
    sales_month,
    ROUND(monthly_revenue, 2) AS monthly_revenue,
    ROUND(
        SUM(monthly_revenue) OVER (
            PARTITION BY sales_year 
            ORDER BY sales_month_num
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ), 2
    ) AS cumulative_yearly_sales
FROM 
    monthly_sales
ORDER BY 
    sales_year, 
    sales_month_num;

#------------------------------------------------------------------------------------------------------
#3. Calculate the year-over-year growth rate of total sales. 
WITH annual_revenue AS (
    SELECT 
        YEAR(o.order_purchase_timestamp) AS sales_year,
        SUM(oi.price) AS total_sales
    FROM 
        orders o
    JOIN 
        order_items oi ON o.order_id = oi.order_id
    WHERE 
        o.order_status NOT IN ('canceled', 'unavailable') -- Standard data cleaning
    GROUP BY 
        YEAR(o.order_purchase_timestamp)
)
SELECT 
    sales_year,
    ROUND(total_sales, 2) AS current_year_sales,
    ROUND(LAG(total_sales) OVER (ORDER BY sales_year), 2) AS previous_year_sales,
    ROUND(
        100.0 * (total_sales - LAG(total_sales) OVER (ORDER BY sales_year)) / 
        LAG(total_sales) OVER (ORDER BY sales_year), 
        2
    ) AS yoy_growth_rate_pct
FROM 
    annual_revenue
ORDER BY 
    sales_year;
#---------------------------------------------------------------------------------------------------------------
#4. Calculate the retention rate of customers, defined as the percentage of customers who make another purchase 
#within 6 months of their first purchase
WITH customer_orders AS (
    SELECT 
        c.customer_unique_id,
        o.order_id,
        o.order_purchase_timestamp,
        -- Find the first ever purchase date for this unique customer
        MIN(o.order_purchase_timestamp) OVER(PARTITION BY c.customer_unique_id) AS first_purchase_date
    FROM 
        orders o
    JOIN 
        customers c ON o.customer_id = c.customer_id
    WHERE 
        o.order_status NOT IN ('canceled', 'unavailable')
),
retention_flags AS (
    SELECT 
        customer_unique_id,
        -- Flag 1 if a secondary order exists within a strict 6-month (180 days) window
        MAX(CASE 
            WHEN DATEDIFF(order_purchase_timestamp, first_purchase_date) BETWEEN 1 AND 180 
            THEN 1 ELSE 0 
        END) AS retained_within_6m
    FROM 
        customer_orders
    GROUP BY 
        customer_unique_id
)
SELECT 
    COUNT(DISTINCT customer_unique_id) AS total_unique_customers,
    SUM(retained_within_6m) AS retained_customers_count,
    ROUND(100.0 * SUM(retained_within_6m) / COUNT(DISTINCT customer_unique_id), 2) AS retention_rate_percentage
FROM 
    retention_flags;

#------------------------------------------------------------------------------------
#5. Identify the top 3 customers who spent the most money in each year.
WITH annual_customer_spending AS (
    SELECT 
        YEAR(o.order_purchase_timestamp) AS sales_year,
        c.customer_unique_id,
        ROUND(SUM(oi.price), 2) AS total_spent,
        COUNT(DISTINCT o.order_id) AS total_orders_placed
    FROM 
        orders o
    JOIN 
        order_items oi ON o.order_id = oi.order_id
    JOIN 
        customers c ON o.customer_id = c.customer_id
    WHERE 
        o.order_status NOT IN ('canceled', 'unavailable')
    GROUP BY 
        YEAR(o.order_purchase_timestamp),
        c.customer_unique_id
),
ranked_whales AS (
    SELECT 
        sales_year,
        customer_unique_id,
        total_spent,
        total_orders_placed,
        DENSE_RANK() OVER (PARTITION BY sales_year ORDER BY total_spent DESC) AS spending_rank
    FROM 
        annual_customer_spending
)
SELECT 
    sales_year,
    spending_rank,
    customer_unique_id,
    total_spent,
    total_orders_placed
FROM 
    ranked_whales
WHERE 
    spending_rank <= 3
ORDER BY 
    sales_year ASC, 
    spending_rank ASC;
